services:

  proxy:
    hostname: proxy
    container_name: proxy
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

  rinha-db:
    image: postgres:17-alpine
    container_name: rinha-database
    hostname: rinha-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=rinha-password-db!@
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "40MB"

  backend1: &api-template
    image: leoof/rinha-backend
    container_name: backend1
    hostname: backend1
    restart: always
    depends_on:
      - rinha-db
    ports:
      - 3000:8080
    environment:
      - ConnectionStrings__Database=Server=rinha-db;Port=5432;Database=rinha;UserId=postgres;Password=rinha-password-db!@
      - Service__PaymentProcessorDefault__BASE_URL=http://payment-processor-default:8080
      - Service__PaymentProcessorFallback__BASE_URL=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "144MB"

  backend2:
    <<: *api-template
    container_name: backend2
    hostname: backend2
    ports:
      - '3001:8080'
    environment:
      - ConnectionStrings__Database=Server=rinha-db;Port=5432;Database=rinha;UserId=postgres;Password=rinha-password-db!@
      - Service__PaymentProcessorDefault__BASE_URL=http://payment-processor-default:8080
      - Service__PaymentProcessorFallback__BASE_URL=http://payment-processor-fallback:8080

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true